// Shared TRON test fixtures (not a test file itself).
//
// TRON_VECTORS is copied VERBATIM from ~/repos/tron-ssp-vectors.json
// (TRON_SSP_CONTRACT.md §2; generated by ~/repos/tron-ssp-vectors.mjs). Every
// SSP repo must reproduce it exactly. factory / implementation are the SDK's
// fixed TEST labels, not deployments; chainId is mainnet's.
import * as T from '@runonflux/tron-multisig';
import { HDKey } from '@scure/bip32';
import { blockchains } from '@storage/blockchains';
import { getMasterXpriv, getMasterXpub } from '../../src/lib/wallet';
import { tronConsumerVault } from '../../src/lib/tron';

export const TRON_VECTORS = {
  _about:
    "SSP TRON cross-repo vectors. BIP-48 m/48'/195'/{account}'/0'/{a}/{b}. factory THEmkX\u2026 / implementation TJEfVH\u2026 are fixed SDK test labels, chainId = mainnet 728126428.",
  network: {
    chainId: '728126428',
    factory: 'THEmkXNjoxz6zj7wDBtXRd1DCYeLTvRYSB',
    implementation: 'TJEfVHrNkFfPdyNVFmY8cvJPm77rDQfSn3',
  },
  consumer: {
    walletXpub:
      'xpub6DugByuv8jZ582WqjRXeieyXbrsEdQvnuF6TfF2YGZW8LmrGQ6E1HGcRA7zrsX2uRLSpMEHwnpc5np6odeCJBhwcXi1MBDtwikT4MbfK8Uo',
    keyXpub:
      'xpub6EEnUgN1rd2paX4iybUKeC5qeiXxYv7jBCVawi1a3HnTfycaUGn2s2xWcBX7jcE7M18EJLw3HUJa9iG9vVRQTMa5bcZDpTzGyh8iBMARBS3',
    leaves: {
      '0-0': {
        walletSigner: 'TCKJLxzMRF1hKKCjPSnWM6tDunYND891w8',
        keySigner: 'TNpFc6D1wF1NEZVdX1nPTm1yPPX3tUm1sV',
        signers: [
          'TCKJLxzMRF1hKKCjPSnWM6tDunYND891w8',
          'TNpFc6D1wF1NEZVdX1nPTm1yPPX3tUm1sV',
        ],
        threshold: 2,
        configHash:
          '0x2b1290c202073dc15d2ade4f480896801cecfbd9db1ce51e9cd42710f35d3ca2',
        address: 'TWq9eJbomJDmkME7ahC4renGL2BXacL2vd',
      },
      '0-1': {
        walletSigner: 'TRkASZyzHKGDpkoLXS73JhkshwjxUYwYsS',
        keySigner: 'TV9a3RCFeZ2MpkRaccPSEFxrW5GHiXMBdF',
        signers: [
          'TRkASZyzHKGDpkoLXS73JhkshwjxUYwYsS',
          'TV9a3RCFeZ2MpkRaccPSEFxrW5GHiXMBdF',
        ],
        threshold: 2,
        configHash:
          '0xba8910adb75b5eba9759437bd75ee55832abf58ca3b48ee6e50c0e567e610755',
        address: 'TX6gBaQcsAZyTmPzoGT6MLHPQQwsvbrJ8u',
      },
      '1-0': {
        walletSigner: 'TQKZcFAnHjqybYUPsZFbaZ7u1TAyMCm1wF',
        keySigner: 'TWsqqV1ugkX1bZP4JDzT44MwPSRuzfaaPE',
        signers: [
          'TQKZcFAnHjqybYUPsZFbaZ7u1TAyMCm1wF',
          'TWsqqV1ugkX1bZP4JDzT44MwPSRuzfaaPE',
        ],
        threshold: 2,
        configHash:
          '0xe59100d2a1324a40240978a5476835bcca7840ecb436ee438b735cee91d7ad56',
        address: 'TEbVYCR2mXsNLbnkZRZQE1nJsryXUxTaou',
      },
    },
  },
  enterpriseSingle2of3: {
    orgIndex: 100,
    vaultIndex: 0,
    addressIndex: 0,
    signerXpubs: [
      'xpub6EZMHM4C8bThZ5uZFaYXEnqhciHRpLttAmysQqAgapkbVPZ8grZBTNhTPYsqpNHfDGVY27s4strsC2ri6E15miziBrrwhFHGkvodV42TdNC',
      'xpub6Egt1vChFgn9AySQkqsdbUmmhz8ss7mQstycTyDTewFhVuQpX9eq9kY2N4kwyUyhWGQGW2CXstRwRZVnisUXsNBAhoxiDdgunP525vymZSE',
      'xpub6Dsisqu5WXsG6xo4KctbXbL516DapH9k1GyAr9aKSKmfvoxecps3HyBM44aMfRfztM3jjcHmWHbNW4JModpG7BUnDBMjeVeg7DQqG7yZ5YD',
    ],
    signers: [
      'TECBSS5N1ospYVfNAejCKEc84dnzcXF8q6',
      'THiAbe1CHf8DaZtBzP1Uyh3cduvhDDyPN7',
      'TYqfa3eUpSiKMSw5zFRtjJKkdjesUpS9pG',
    ],
    threshold: 2,
    configHash:
      '0xbab30ae4d2ebbaf878b3a448813248e645f3c9e35ce72b251df85824af5a9787',
    address: 'TEpeXgvKdyvuLPL54ZaavjzKUw9o6CTrGC',
  },
  enterpriseDual2of2: {
    orgIndex: 100,
    vaultIndex: 0,
    addressIndex: 0,
    requiredSigners: 2,
    signers: [
      'TCyygaR2vZ3h4gumtesmG4jqckg52fqnnc',
      'TECBSS5N1ospYVfNAejCKEc84dnzcXF8q6',
      'THiAbe1CHf8DaZtBzP1Uyh3cduvhDDyPN7',
      'TYqfa3eUpSiKMSw5zFRtjJKkdjesUpS9pG',
    ],
    threshold: 4,
    configHash:
      '0x9da91acae68cd12c6c2fc7e1ec26c15e49b14b6c9e5d9a045ac31e1fb82b00cb',
    address: 'TFYDwwuj2h6CUXVMHKkAzKFThKjiXHeysr',
  },
  consumerOp: {
    leaf: '0-0',
    vault: 'TWq9eJbomJDmkME7ahC4renGL2BXacL2vd',
    op: {
      calls: [
        {
          to: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
          value: '0',
          data: '0xa9059cbb0000000000000000000000004a444867aba3ad826169f44898662403de1c47bf00000000000000000000000000000000000000000000000000000000017d7840',
          tokenId: '0',
          tokenValue: '0',
        },
      ],
      nonce: '7',
      deadline: '1790000000',
      fee: {
        token: 'T9yD14Nj9j7xAB4dbGeiX9h8unkKHxuWwb',
        amount: '6300000',
        recipient: 'TFhcYVArFkJW6bPUDid4AFCAjKmh6Ez3vv',
      },
    },
    domainSeparator:
      '0x9980294a23cdbbd0e0f2a08468c7c4775a4816ca54aa7220322a8e0229922340',
    digest:
      '0x5792bc619441f3f65ee8a181e43fbbc1bccd49eb1ed0afa6f9a51e855bd6065c',
    walletSignature:
      '0x97428cf0ec6116a33cd4239d8f88c20eb86c6feaecdc7425337af866a91961432c678699aef7b7a28f025cf0fa85843393d6e2ba0f9d34abb22018762fcd72c01b',
    keySignature:
      '0x5857e0b61344f0f04434206dcc39e2be6c3240f3560835f22b934be22658ae6555e06ccf4057752d4085b614bb291d33408245f91994b899c45edf2b23312f1e1c',
    signaturesPacked:
      '0x97428cf0ec6116a33cd4239d8f88c20eb86c6feaecdc7425337af866a91961432c678699aef7b7a28f025cf0fa85843393d6e2ba0f9d34abb22018762fcd72c01b5857e0b61344f0f04434206dcc39e2be6c3240f3560835f22b934be22658ae6555e06ccf4057752d4085b614bb291d33408245f91994b899c45edf2b23312f1e1c',
    executeCalldata:
      '0x42a0c5570000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000002819bd07f6731f6a21d245f1e59034a53f563062818ce810b35dfea6d49a2eb9c94bf26e32530687e400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000006ab13b80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006021600000000000000000000000003eddc045b5d4038013c8815ec3f5a3621fe2044700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000a614f803b6fd780986a42c78ec9c7f77e6ded13c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a9059cbb0000000000000000000000004a444867aba3ad826169f44898662403de1c47bf00000000000000000000000000000000000000000000000000000000017d784000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008297428cf0ec6116a33cd4239d8f88c20eb86c6feaecdc7425337af866a91961432c678699aef7b7a28f025cf0fa85843393d6e2ba0f9d34abb22018762fcd72c01b5857e0b61344f0f04434206dcc39e2be6c3240f3560835f22b934be22658ae6555e06ccf4057752d4085b614bb291d33408245f91994b899c45edf2b23312f1e1c000000000000000000000000000000000000000000000000000000000000',
  },
} as const;

/** BIP-39 test mnemonics (the Kaspa set) — never fund them. */
export const MNEMONIC_W =
  'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about';
export const MNEMONIC_KK =
  'legal winner thank year wave sausage worth useful legal winner thank yellow';
export const MNEMONIC_S3 =
  'letter advice cage absurd amount doctor acoustic avoid letter advice cage above';
export const MNEMONIC_Z = 'zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo wrong';

export const TRON = 'tron';

/** The fee collector the vector Op pays (a fixed test address). */
export const VECTOR_FEE_COLLECTOR = 'TFhcYVArFkJW6bPUDid4AFCAjKmh6Ez3vv';
/** The vector Op's recipient. */
export const VECTOR_RECIPIENT = 'TGjtodRV2nm6tQd9hsxiecLNN9QmhhVbbD';
/** A fixed test sponsor label (only its presence matters to isTronLive). */
export const VECTOR_SPONSOR = T.addressFromBytes20(
  new Uint8Array(20).fill(0x55),
);

/**
 * The explicit NetworkConfig the vectors were generated with: mainnet's
 * chainId + USDT and the fixed factory / implementation test labels, plus the
 * vector fee collector (and a sponsor label) so the network counts as live.
 */
export const VECTOR_NETWORK: T.NetworkConfig = T.getNetwork({
  ...T.NETWORKS.mainnet,
  name: 'ssp-vectors',
  factory: TRON_VECTORS.network.factory,
  implementation: TRON_VECTORS.network.implementation,
  sponsor: VECTOR_SPONSOR,
  feeCollector: VECTOR_FEE_COLLECTOR,
});

/** Vector time: 30 minutes before the vector Op's deadline (1790000000). */
export const VECTOR_NOW = 1790000000n - 1800n;

export function tronXpub(mnemonic: string, account: number): string {
  return getMasterXpub(mnemonic, 48, 195, account, 'p2sh', TRON);
}

export function tronXpriv(mnemonic: string, account: number): string {
  return getMasterXpriv(mnemonic, 48, 195, account, 'p2sh', TRON);
}

/** The raw leaf private key m/48'/195'/{account}'/0'/a/b of a test mnemonic. */
export function leafPriv(
  mnemonic: string,
  account: number,
  a: number,
  b: number,
) {
  const node = HDKey.fromExtendedKey(
    tronXpriv(mnemonic, account),
    blockchains[TRON].bip32,
  )
    .deriveChild(a)
    .deriveChild(b);
  return node.privateKey as Uint8Array;
}

/** A consumer payload for leaf 0-i, signed by the WALLET (mnemonic W). */
export function consumerPayload(
  op: T.Op,
  overrides: Record<string, unknown> = {},
  opts: { addressIndex?: number; signWith?: Uint8Array } = {},
): string {
  const i = opts.addressIndex ?? 0;
  const own = tronConsumerVault(
    TRON_VECTORS.consumer.walletXpub,
    TRON_VECTORS.consumer.keyXpub,
    0,
    i,
    TRON,
    VECTOR_NETWORK,
  );
  const digest = T.opDigest(VECTOR_NETWORK.chainId, own.vault.address, op);
  const signer = T.localSigner(opts.signWith ?? leafPriv(MNEMONIC_W, 0, 0, i));
  const walletSignature = T.to0x(signer.signDigest(digest));
  signer.destroy();
  return JSON.stringify({
    format: 'ssp-tron-op',
    version: 1,
    network: 'ssp-vectors',
    vault: own.vault.address,
    signers: own.config.signers,
    threshold: own.config.threshold,
    op: T.opToJson(op),
    walletSignature,
    ...overrides,
  });
}
