name: android-build-self
on:
  push:
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: ssp-key-android
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"
      - name: Install npm dependencies
        run: |
          yarn
      - name: Run Test Suite
        run: |
          yarn test:report
  build-android:
    needs: install-and-test
    runs-on: ssp-key-android
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "release.keystore"
          fileDir: "/home/user/actions-runner/_work/ssp-key/ssp-key/android/app/"
          encodedString: ${{ secrets.ANDROID_SIGNING_KEY }}
      - name: Build Android APK Release
        run: |
          cd android && ./gradlew clean && ./gradlew generateCodegenArtifactsFromSchema --rerun-tasks && ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
      - name: Build Android ABB Release
        run: |
          cd android && ./gradlew bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
